PrimerMVCCore/Models/ErrorViewModel.cs
using System;

namespace PrimerMVCCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrimerMVCCore/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerMVCCore.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public int Edad { get; set; }
        public string Genero { get; set; }

    }
}

PrimerMVCCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PrimerMVCCore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerMVCCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrimerMVCCore/Controllers/InformacionController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMVCCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrimerMVCCore.Controllers
{
    public class InformacionController : Controller
    {
        public IActionResult VistaPost()
        {
            return View();
        }
        [HttpPost]
        public IActionResult VistaPost(string cajanombre, string cajaedad)
        {
            ViewBag.Nombre = cajanombre;
            ViewBag.Edad = cajaedad;
            return View();
        }
        public IActionResult VistaDatos(string aplicacion, int version)
        {
            ViewBag.Aplicacion = aplicacion;
            ViewBag.Version = version;
            return View();
        }
        public IActionResult Inicio()
        {
            ViewBag.Nombre = "Alumno";
            ViewBag.Edad = 19;
            Persona person = new Persona();
            person.Nombre = "Modelo";
            person.Edad = 111;
            person.Genero = "Dunno";
            return View(person);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

PrimerMVCCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PrimerMVCCore/Views/Informacion/Inicio.cshtml
@*COMENTARIOS EN RAZOR*@
@{
    @*DECIARACION DE VARIABLES EN RAZOR*@
    int numero = 14;
    string texto = "TEXTO";

}
@model Persona
<!--Dibujar variables:-->
<h1 style="color:Highlight">@texto</h1>
<!--CODIGO LOGICO-->
@if (numero > 0)
{
    //ESTO ES CODIGO DE SERVIDOR.
    //CUANDO ESCRIBIMOS CARACTERES HTML, SE CORTA EL CODIGO LOGICO Y SE EMPIEZA EL DIBUJO
    <h2>Positivo @numero</h2>
}
else
{
    <h2>Negativo @numero</h2>
}

<h1 style="color:fuchsia">
    Mi primera vista MVC
</h1>
<h1>Nombre: @ViewBag.Nombre
    Edad:@ViewBag.Edad</h1>
<hr />
<h1>PERSONA</h1>
<h2>@Model.Nombre,@Model.Genero, @Model.Edad </h2>

PrimerMVCCore/Views/Informacion/VistaDatos.cshtml
<h1>Vista para enviar info al controller</h1>
<h2 style="color:firebrick">Su aplicacion es: @ViewBag.Aplicacion con versión @ViewBag.Version</h2>

PrimerMVCCore/Views/Informacion/VistaPost.cshtml
<h1>Informacion metodo POST</h1>
<form method="POST">
    <label>Nombre:</label>
    <input type="text" name="cajanombre" class="form-control" /><br />
    <label>Edad:</label>
    <input type="text" name="cajaedad" class="form-control" /><br />
<button type="submit" class="btn btn-success">Submit</button>
</form>
<h1>@ViewBag.Nombre, @ViewBag.Edad</h1>

PrimerMVCCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerMVCCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Esto es un Core pre Natale</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Informacion" asp-action="Inicio">Inicio</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Informacion" asp-action="VistaDatos">VistaDatos</a>
                            @Html.ActionLink("Action Vista Datos", "VistaDatos", "Informacion", new {aplicacion="Net Core", version=4 })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Action Vista Post", "VistaPost", "Informacion")
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PrimerMVCCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>